apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec: 
      containers:
        - name: expiration
          image: lilianalessa1/microservices_course_ticketing_expiration
          env: 
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'ticketing' #from infra/k8s/nats-depl.yaml > spec.template.spec.containers[0].args['-cid']. cid stands for cluster id
            - name: REDIS_HOST
              value: 'expiration-redis-srv'
      