name:  tests ticketing/tickets

on:
  pull_request

defaults:
  run:
    working-directory: ./ticketing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
